php-7.0-linting:
  image: php:7.0
  script:
    - sh -c 'if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -v "^No syntax errors detected"; then exit 1; fi'

php-7.1-linting:
  image: php:7.1
  script:
    - sh -c 'if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -v "^No syntax errors detected"; then exit 1; fi'

php-7.2-linting:
  image: php:7.2
  script:
    - sh -c 'if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -v "^No syntax errors detected"; then exit 1; fi'

php-7.2-phpcs:
  image: yireo/php-testbox:7.2
  script:
    - phpcs --colors --standard=PSR2 --report=full .
    - composer validate
